### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by PoonamZ** [zsdonghao/u-net-brain-tumor#28]
@zsdonghao I am getting the memory error like this, What is the solution for this error? 

Traceback (most recent call last):
  File "train.py", line 279, in <module>
    main(args.task)
  File "train.py", line 78, in main
    y_test = (y_test > 0).astype(int)
MemoryError

**Comment by PoonamZ** [comment]
@zsdonghao now I am getting the error like this. Please, Can you suggest the solution for this?

2018-04-29 04:59:36.049069: E tensorflow/stream_executor/cuda/cuda_driver.cc:967] failed to alloc 1073741824 bytes on host: CUDA_ERROR_OUT_OF_MEMORY
2018-04-29 04:59:36.113696: W ./tensorflow/core/common_runtime/gpu/pool_allocator.h:195] could not allocate pinned host memory of size: 1073741824
2018-04-29 04:59:36.114341: E tensorflow/stream_executor/cuda/cuda_driver.cc:967] failed to alloc 966367744 bytes on host: CUDA_ERROR_OUT_OF_MEMORY
2018-04-29 04:59:36.114364: W ./tensorflow/core/common_runtime/gpu/pool_allocator.h:195] could not allocate pinned host memory of size: 966367744
2018-04-29 04:59:36.114892: E tensorflow/stream_executor/cuda/cuda_driver.cc:967] failed to alloc 869731072 bytes on host: CUDA_ERROR_OUT_OF_MEMORY
2018-04-29 04:59:36.114909: W ./tensorflow/core/common_runtime/gpu/pool_allocator.h:195] could not allocate pinned host memory of size: 869731072
2018-04-29 04:59:36.115443: E tensorflow/stream_executor/cuda/cuda_driver.cc:967] failed to alloc 782758144 bytes on host: CUDA_ERROR_OUT_OF_MEMORY
2018-04-29 04:59:36.115461: W ./tensorflow/core/common_runtime/gpu/pool_allocator.h:195] could not allocate pinned host memory of size: 782758144
Killed

**Comment by zsdonghao** [comment]
I think you need more memory, or reimplement the way to read data e.g. TF datasets, TFRecord

**Comment by PoonamZ** [comment]
@zsdonghao Can you please share the checkpoints for edema, necrotic and enhanced.
Thank you so much.

**Comment by PoonamZ** [comment]
@zsdonghao please can u share me the checkpoints .
Thank you
